// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: github.com/hmartins98/Contracts/Items/Items.proto

package Items

import (
	CustomTypes "github.com/hmartins98/Contracts/CustomTypes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Items struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *CustomTypes.GUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeId      int32             `protobuf:"varint,4,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Price       float32           `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Description string            `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	ReviewScore float32           `protobuf:"fixed32,7,opt,name=review_score,json=reviewScore,proto3" json:"review_score,omitempty"`
}

func (x *Items) Reset() {
	*x = Items{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_Items_Items_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_Items_Items_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_Items_Items_proto_rawDescGZIP(), []int{0}
}

func (x *Items) GetId() *CustomTypes.GUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Items) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Items) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *Items) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Items) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Items) GetReviewScore() float32 {
	if x != nil {
		return x.ReviewScore
	}
	return 0
}

type ItemsId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *CustomTypes.GUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ItemsId) Reset() {
	*x = ItemsId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_Items_Items_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemsId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsId) ProtoMessage() {}

func (x *ItemsId) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_Items_Items_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsId.ProtoReflect.Descriptor instead.
func (*ItemsId) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_Items_Items_proto_rawDescGZIP(), []int{1}
}

func (x *ItemsId) GetId() *CustomTypes.GUID {
	if x != nil {
		return x.Id
	}
	return nil
}

var File_github_com_hmartins98_Contracts_Items_Items_proto protoreflect.FileDescriptor

var file_github_com_hmartins98_Contracts_Items_Items_proto_rawDesc = []byte{
	0x0a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6d, 0x61,
	0x72, 0x74, 0x69, 0x6e, 0x73, 0x39, 0x38, 0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x2f, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x2f, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x1a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6d,
	0x61, 0x72, 0x74, 0x69, 0x6e, 0x73, 0x39, 0x38, 0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xa6, 0x01, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x15, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x47, 0x55, 0x49, 0x44, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x20, 0x0a, 0x07, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x47, 0x55, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x32, 0xbd, 0x01, 0x0a, 0x0d,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x29, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x13, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x1a, 0x05, 0x2e, 0x42, 0x4f, 0x4f, 0x4c, 0x12, 0x29, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x15, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x64, 0x1a, 0x05, 0x2e, 0x42,
	0x4f, 0x4f, 0x4c, 0x12, 0x29, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x13, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x05, 0x2e, 0x42, 0x4f, 0x4f, 0x4c, 0x12, 0x2b,
	0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x15, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x49, 0x64, 0x1a, 0x05, 0x2e, 0x42, 0x4f, 0x4f, 0x4c, 0x42, 0x11, 0x5a, 0x0f, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_hmartins98_Contracts_Items_Items_proto_rawDescOnce sync.Once
	file_github_com_hmartins98_Contracts_Items_Items_proto_rawDescData = file_github_com_hmartins98_Contracts_Items_Items_proto_rawDesc
)

func file_github_com_hmartins98_Contracts_Items_Items_proto_rawDescGZIP() []byte {
	file_github_com_hmartins98_Contracts_Items_Items_proto_rawDescOnce.Do(func() {
		file_github_com_hmartins98_Contracts_Items_Items_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_hmartins98_Contracts_Items_Items_proto_rawDescData)
	})
	return file_github_com_hmartins98_Contracts_Items_Items_proto_rawDescData
}

var file_github_com_hmartins98_Contracts_Items_Items_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_hmartins98_Contracts_Items_Items_proto_goTypes = []interface{}{
	(*Items)(nil),            // 0: ItemsPackage.Items
	(*ItemsId)(nil),          // 1: ItemsPackage.ItemsId
	(*CustomTypes.GUID)(nil), // 2: GUID
	(*CustomTypes.BOOL)(nil), // 3: BOOL
}
var file_github_com_hmartins98_Contracts_Items_Items_proto_depIdxs = []int32{
	2, // 0: ItemsPackage.Items.id:type_name -> GUID
	2, // 1: ItemsPackage.ItemsId.id:type_name -> GUID
	0, // 2: ItemsPackage.ItemsContract.CreateItems:input_type -> ItemsPackage.Items
	1, // 3: ItemsPackage.ItemsContract.ReadItems:input_type -> ItemsPackage.ItemsId
	0, // 4: ItemsPackage.ItemsContract.UpdateItems:input_type -> ItemsPackage.Items
	1, // 5: ItemsPackage.ItemsContract.DeleteItems:input_type -> ItemsPackage.ItemsId
	3, // 6: ItemsPackage.ItemsContract.CreateItems:output_type -> BOOL
	3, // 7: ItemsPackage.ItemsContract.ReadItems:output_type -> BOOL
	3, // 8: ItemsPackage.ItemsContract.UpdateItems:output_type -> BOOL
	3, // 9: ItemsPackage.ItemsContract.DeleteItems:output_type -> BOOL
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_hmartins98_Contracts_Items_Items_proto_init() }
func file_github_com_hmartins98_Contracts_Items_Items_proto_init() {
	if File_github_com_hmartins98_Contracts_Items_Items_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_hmartins98_Contracts_Items_Items_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Items); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_Items_Items_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemsId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_hmartins98_Contracts_Items_Items_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_hmartins98_Contracts_Items_Items_proto_goTypes,
		DependencyIndexes: file_github_com_hmartins98_Contracts_Items_Items_proto_depIdxs,
		MessageInfos:      file_github_com_hmartins98_Contracts_Items_Items_proto_msgTypes,
	}.Build()
	File_github_com_hmartins98_Contracts_Items_Items_proto = out.File
	file_github_com_hmartins98_Contracts_Items_Items_proto_rawDesc = nil
	file_github_com_hmartins98_Contracts_Items_Items_proto_goTypes = nil
	file_github_com_hmartins98_Contracts_Items_Items_proto_depIdxs = nil
}
