// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: github.com/hmartins98/Contracts/CMS/CMS.proto

package CMS

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_ "github.com/hmartins98/Contracts/CustomTypes"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ActivityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int32 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
}

func (x *ActivityRequest) Reset() {
	*x = ActivityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityRequest) ProtoMessage() {}

func (x *ActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityRequest.ProtoReflect.Descriptor instead.
func (*ActivityRequest) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityRequest) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type ActivityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Activity *LinearLayoutProperties `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
}

func (x *ActivityReply) Reset() {
	*x = ActivityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityReply) ProtoMessage() {}

func (x *ActivityReply) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityReply.ProtoReflect.Descriptor instead.
func (*ActivityReply) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityReply) GetActivity() *LinearLayoutProperties {
	if x != nil {
		return x.Activity
	}
	return nil
}

type ViewProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Gravity      int32 `protobuf:"varint,2,opt,name=gravity,proto3" json:"gravity,omitempty"`
	Height       int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Width        int32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	MarginStart  int32 `protobuf:"varint,5,opt,name=marginStart,proto3" json:"marginStart,omitempty"`
	MarginEnd    int32 `protobuf:"varint,6,opt,name=marginEnd,proto3" json:"marginEnd,omitempty"`
	MarginLeft   int32 `protobuf:"varint,7,opt,name=marginLeft,proto3" json:"marginLeft,omitempty"`
	MarginTop    int32 `protobuf:"varint,8,opt,name=marginTop,proto3" json:"marginTop,omitempty"`
	MarginRight  int32 `protobuf:"varint,9,opt,name=marginRight,proto3" json:"marginRight,omitempty"`
	MarginBottom int32 `protobuf:"varint,10,opt,name=marginBottom,proto3" json:"marginBottom,omitempty"`
}

func (x *ViewProperties) Reset() {
	*x = ViewProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewProperties) ProtoMessage() {}

func (x *ViewProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewProperties.ProtoReflect.Descriptor instead.
func (*ViewProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{2}
}

func (x *ViewProperties) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ViewProperties) GetGravity() int32 {
	if x != nil {
		return x.Gravity
	}
	return 0
}

func (x *ViewProperties) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ViewProperties) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ViewProperties) GetMarginStart() int32 {
	if x != nil {
		return x.MarginStart
	}
	return 0
}

func (x *ViewProperties) GetMarginEnd() int32 {
	if x != nil {
		return x.MarginEnd
	}
	return 0
}

func (x *ViewProperties) GetMarginLeft() int32 {
	if x != nil {
		return x.MarginLeft
	}
	return 0
}

func (x *ViewProperties) GetMarginTop() int32 {
	if x != nil {
		return x.MarginTop
	}
	return 0
}

func (x *ViewProperties) GetMarginRight() int32 {
	if x != nil {
		return x.MarginRight
	}
	return 0
}

func (x *ViewProperties) GetMarginBottom() int32 {
	if x != nil {
		return x.MarginBottom
	}
	return 0
}

type LinearLayoutProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View        *ViewProperties `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Orientation int32           `protobuf:"varint,2,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Views       []*any.Any      `protobuf:"bytes,3,rep,name=views,proto3" json:"views,omitempty"`
}

func (x *LinearLayoutProperties) Reset() {
	*x = LinearLayoutProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinearLayoutProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearLayoutProperties) ProtoMessage() {}

func (x *LinearLayoutProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearLayoutProperties.ProtoReflect.Descriptor instead.
func (*LinearLayoutProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{3}
}

func (x *LinearLayoutProperties) GetView() *ViewProperties {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *LinearLayoutProperties) GetOrientation() int32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

func (x *LinearLayoutProperties) GetViews() []*any.Any {
	if x != nil {
		return x.Views
	}
	return nil
}

type ImageProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View      *ViewProperties `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Uri       string          `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	ScaleType int32           `protobuf:"varint,3,opt,name=scaleType,proto3" json:"scaleType,omitempty"`
}

func (x *ImageProperties) Reset() {
	*x = ImageProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageProperties) ProtoMessage() {}

func (x *ImageProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageProperties.ProtoReflect.Descriptor instead.
func (*ImageProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{4}
}

func (x *ImageProperties) GetView() *ViewProperties {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *ImageProperties) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ImageProperties) GetScaleType() int32 {
	if x != nil {
		return x.ScaleType
	}
	return 0
}

type TextProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View *ViewProperties `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Text string          `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TextProperties) Reset() {
	*x = TextProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextProperties) ProtoMessage() {}

func (x *TextProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextProperties.ProtoReflect.Descriptor instead.
func (*TextProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{5}
}

func (x *TextProperties) GetView() *ViewProperties {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *TextProperties) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ButtonProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View            *ViewProperties `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Text            string          `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	BackgroundColor int32           `protobuf:"varint,3,opt,name=backgroundColor,proto3" json:"backgroundColor,omitempty"`
	TextColor       int32           `protobuf:"varint,4,opt,name=textColor,proto3" json:"textColor,omitempty"`
	// Types that are assignable to Action:
	//	*ButtonProperties_ChangeActivityInteraction
	//	*ButtonProperties_RecyclerViewInteraction
	//	*ButtonProperties_SubmitInteraction
	Action isButtonProperties_Action `protobuf_oneof:"action"`
}

func (x *ButtonProperties) Reset() {
	*x = ButtonProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ButtonProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonProperties) ProtoMessage() {}

func (x *ButtonProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonProperties.ProtoReflect.Descriptor instead.
func (*ButtonProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{6}
}

func (x *ButtonProperties) GetView() *ViewProperties {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *ButtonProperties) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ButtonProperties) GetBackgroundColor() int32 {
	if x != nil {
		return x.BackgroundColor
	}
	return 0
}

func (x *ButtonProperties) GetTextColor() int32 {
	if x != nil {
		return x.TextColor
	}
	return 0
}

func (m *ButtonProperties) GetAction() isButtonProperties_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *ButtonProperties) GetChangeActivityInteraction() *ChangeActivityInteraction {
	if x, ok := x.GetAction().(*ButtonProperties_ChangeActivityInteraction); ok {
		return x.ChangeActivityInteraction
	}
	return nil
}

func (x *ButtonProperties) GetRecyclerViewInteraction() *RecyclerViewInteraction {
	if x, ok := x.GetAction().(*ButtonProperties_RecyclerViewInteraction); ok {
		return x.RecyclerViewInteraction
	}
	return nil
}

func (x *ButtonProperties) GetSubmitInteraction() *SubmitInteraction {
	if x, ok := x.GetAction().(*ButtonProperties_SubmitInteraction); ok {
		return x.SubmitInteraction
	}
	return nil
}

type isButtonProperties_Action interface {
	isButtonProperties_Action()
}

type ButtonProperties_ChangeActivityInteraction struct {
	ChangeActivityInteraction *ChangeActivityInteraction `protobuf:"bytes,5,opt,name=change_activity_interaction,json=changeActivityInteraction,proto3,oneof"`
}

type ButtonProperties_RecyclerViewInteraction struct {
	RecyclerViewInteraction *RecyclerViewInteraction `protobuf:"bytes,6,opt,name=recycler_view_interaction,json=recyclerViewInteraction,proto3,oneof"`
}

type ButtonProperties_SubmitInteraction struct {
	SubmitInteraction *SubmitInteraction `protobuf:"bytes,7,opt,name=submit_interaction,json=submitInteraction,proto3,oneof"`
}

func (*ButtonProperties_ChangeActivityInteraction) isButtonProperties_Action() {}

func (*ButtonProperties_RecyclerViewInteraction) isButtonProperties_Action() {}

func (*ButtonProperties_SubmitInteraction) isButtonProperties_Action() {}

type ChangeActivityInteraction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextActivityID int32 `protobuf:"varint,1,opt,name=nextActivityID,proto3" json:"nextActivityID,omitempty"`
}

func (x *ChangeActivityInteraction) Reset() {
	*x = ChangeActivityInteraction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeActivityInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeActivityInteraction) ProtoMessage() {}

func (x *ChangeActivityInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeActivityInteraction.ProtoReflect.Descriptor instead.
func (*ChangeActivityInteraction) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeActivityInteraction) GetNextActivityID() int32 {
	if x != nil {
		return x.NextActivityID
	}
	return 0
}

type RecyclerViewInteraction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecycleViewID int32 `protobuf:"varint,1,opt,name=recycleViewID,proto3" json:"recycleViewID,omitempty"`
	GoTo          int32 `protobuf:"varint,2,opt,name=goTo,proto3" json:"goTo,omitempty"`
}

func (x *RecyclerViewInteraction) Reset() {
	*x = RecyclerViewInteraction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecyclerViewInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecyclerViewInteraction) ProtoMessage() {}

func (x *RecyclerViewInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecyclerViewInteraction.ProtoReflect.Descriptor instead.
func (*RecyclerViewInteraction) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{8}
}

func (x *RecyclerViewInteraction) GetRecycleViewID() int32 {
	if x != nil {
		return x.RecycleViewID
	}
	return 0
}

func (x *RecyclerViewInteraction) GetGoTo() int32 {
	if x != nil {
		return x.GoTo
	}
	return 0
}

type SubmitInteraction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormID int32 `protobuf:"varint,1,opt,name=formID,proto3" json:"formID,omitempty"`
}

func (x *SubmitInteraction) Reset() {
	*x = SubmitInteraction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInteraction) ProtoMessage() {}

func (x *SubmitInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInteraction.ProtoReflect.Descriptor instead.
func (*SubmitInteraction) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitInteraction) GetFormID() int32 {
	if x != nil {
		return x.FormID
	}
	return 0
}

var File_github_com_hmartins98_Contracts_CMS_CMS_proto protoreflect.FileDescriptor

var file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6d, 0x61,
	0x72, 0x74, 0x69, 0x6e, 0x73, 0x39, 0x38, 0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x2f, 0x43, 0x4d, 0x53, 0x2f, 0x43, 0x4d, 0x53, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x1a, 0x3d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6d, 0x61, 0x72, 0x74, 0x69, 0x6e,
	0x73, 0x39, 0x38, 0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x0d, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3f, 0x0a, 0x08, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x69, 0x6e, 0x65,
	0x61, 0x72, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x65, 0x73, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x22, 0xac, 0x02, 0x0a,
	0x0e, 0x56, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x67, 0x72, 0x61, 0x76, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x67, 0x72, 0x61, 0x76, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x67, 0x69,
	0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61,
	0x72, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x72,
	0x67, 0x69, 0x6e, 0x45, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61,
	0x72, 0x67, 0x69, 0x6e, 0x45, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x67, 0x69,
	0x6e, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x72,
	0x67, 0x69, 0x6e, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x67, 0x69,
	0x6e, 0x54, 0x6f, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x72, 0x67,
	0x69, 0x6e, 0x54, 0x6f, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x52,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x72, 0x67,
	0x69, 0x6e, 0x52, 0x69, 0x67, 0x68, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x72, 0x67, 0x69,
	0x6e, 0x42, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d,
	0x61, 0x72, 0x67, 0x69, 0x6e, 0x42, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x22, 0x97, 0x01, 0x0a, 0x16,
	0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65,
	0x73, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6f, 0x72,
	0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x69, 0x65,
	0x77, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05,
	0x76, 0x69, 0x65, 0x77, 0x73, 0x22, 0x72, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x55, 0x0a, 0x0e, 0x54, 0x65, 0x78,
	0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x04, 0x76,
	0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x22, 0xc8, 0x03, 0x0a, 0x10, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x62, 0x61,
	0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0f, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43,
	0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x12, 0x68, 0x0a, 0x1b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x19, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x62, 0x0a, 0x19,
	0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x72, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65,
	0x63, 0x79, 0x63, 0x6c, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x17, 0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x72, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x4f, 0x0a, 0x12, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x11,
	0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x43, 0x0a, 0x19, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x65, 0x78, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x44,
	0x22, 0x53, 0x0a, 0x17, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x72,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x56, 0x69, 0x65, 0x77, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x56, 0x69, 0x65, 0x77, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x54, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x67, 0x6f, 0x54, 0x6f, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d,
	0x49, 0x44, 0x32, 0x59, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x12, 0x1c, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6d, 0x61, 0x72,
	0x74, 0x69, 0x6e, 0x73, 0x39, 0x38, 0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73,
	0x2f, 0x43, 0x4d, 0x53, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescOnce sync.Once
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescData = file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDesc
)

func file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP() []byte {
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescOnce.Do(func() {
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescData)
	})
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescData
}

var file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_github_com_hmartins98_Contracts_CMS_CMS_proto_goTypes = []interface{}{
	(*ActivityRequest)(nil),           // 0: AuthPackage.ActivityRequest
	(*ActivityReply)(nil),             // 1: AuthPackage.ActivityReply
	(*ViewProperties)(nil),            // 2: AuthPackage.ViewProperties
	(*LinearLayoutProperties)(nil),    // 3: AuthPackage.LinearLayoutProperties
	(*ImageProperties)(nil),           // 4: AuthPackage.ImageProperties
	(*TextProperties)(nil),            // 5: AuthPackage.TextProperties
	(*ButtonProperties)(nil),          // 6: AuthPackage.ButtonProperties
	(*ChangeActivityInteraction)(nil), // 7: AuthPackage.ChangeActivityInteraction
	(*RecyclerViewInteraction)(nil),   // 8: AuthPackage.RecyclerViewInteraction
	(*SubmitInteraction)(nil),         // 9: AuthPackage.SubmitInteraction
	(*any.Any)(nil),                   // 10: google.protobuf.Any
}
var file_github_com_hmartins98_Contracts_CMS_CMS_proto_depIdxs = []int32{
	3,  // 0: AuthPackage.ActivityReply.activity:type_name -> AuthPackage.LinearLayoutProperties
	2,  // 1: AuthPackage.LinearLayoutProperties.view:type_name -> AuthPackage.ViewProperties
	10, // 2: AuthPackage.LinearLayoutProperties.views:type_name -> google.protobuf.Any
	2,  // 3: AuthPackage.ImageProperties.view:type_name -> AuthPackage.ViewProperties
	2,  // 4: AuthPackage.TextProperties.view:type_name -> AuthPackage.ViewProperties
	2,  // 5: AuthPackage.ButtonProperties.view:type_name -> AuthPackage.ViewProperties
	7,  // 6: AuthPackage.ButtonProperties.change_activity_interaction:type_name -> AuthPackage.ChangeActivityInteraction
	8,  // 7: AuthPackage.ButtonProperties.recycler_view_interaction:type_name -> AuthPackage.RecyclerViewInteraction
	9,  // 8: AuthPackage.ButtonProperties.submit_interaction:type_name -> AuthPackage.SubmitInteraction
	0,  // 9: AuthPackage.Authentication.GetActivity:input_type -> AuthPackage.ActivityRequest
	1,  // 10: AuthPackage.Authentication.GetActivity:output_type -> AuthPackage.ActivityReply
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_github_com_hmartins98_Contracts_CMS_CMS_proto_init() }
func file_github_com_hmartins98_Contracts_CMS_CMS_proto_init() {
	if File_github_com_hmartins98_Contracts_CMS_CMS_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinearLayoutProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ButtonProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeActivityInteraction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecyclerViewInteraction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitInteraction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*ButtonProperties_ChangeActivityInteraction)(nil),
		(*ButtonProperties_RecyclerViewInteraction)(nil),
		(*ButtonProperties_SubmitInteraction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_hmartins98_Contracts_CMS_CMS_proto_goTypes,
		DependencyIndexes: file_github_com_hmartins98_Contracts_CMS_CMS_proto_depIdxs,
		MessageInfos:      file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes,
	}.Build()
	File_github_com_hmartins98_Contracts_CMS_CMS_proto = out.File
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDesc = nil
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_goTypes = nil
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthenticationClient is the client API for Authentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationClient interface {
	GetActivity(ctx context.Context, in *ActivityRequest, opts ...grpc.CallOption) (*ActivityReply, error)
}

type authenticationClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationClient(cc grpc.ClientConnInterface) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) GetActivity(ctx context.Context, in *ActivityRequest, opts ...grpc.CallOption) (*ActivityReply, error) {
	out := new(ActivityReply)
	err := c.cc.Invoke(ctx, "/AuthPackage.Authentication/GetActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServer is the server API for Authentication service.
type AuthenticationServer interface {
	GetActivity(context.Context, *ActivityRequest) (*ActivityReply, error)
}

// UnimplementedAuthenticationServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServer struct {
}

func (*UnimplementedAuthenticationServer) GetActivity(context.Context, *ActivityRequest) (*ActivityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivity not implemented")
}

func RegisterAuthenticationServer(s *grpc.Server, srv AuthenticationServer) {
	s.RegisterService(&_Authentication_serviceDesc, srv)
}

func _Authentication_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthPackage.Authentication/GetActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).GetActivity(ctx, req.(*ActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AuthPackage.Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActivity",
			Handler:    _Authentication_GetActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/hmartins98/Contracts/CMS/CMS.proto",
}
