// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: github.com/hmartins98/Contracts/CMS/CMS.proto

package CMS

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type InteractionType int32

const (
	InteractionType_CHANGE_ACTIVITY InteractionType = 0
	InteractionType_RECYCLER_VIEW   InteractionType = 1
	InteractionType_SUBMIT          InteractionType = 2
)

// Enum value maps for InteractionType.
var (
	InteractionType_name = map[int32]string{
		0: "CHANGE_ACTIVITY",
		1: "RECYCLER_VIEW",
		2: "SUBMIT",
	}
	InteractionType_value = map[string]int32{
		"CHANGE_ACTIVITY": 0,
		"RECYCLER_VIEW":   1,
		"SUBMIT":          2,
	}
)

func (x InteractionType) Enum() *InteractionType {
	p := new(InteractionType)
	*p = x
	return p
}

func (x InteractionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractionType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[0].Descriptor()
}

func (InteractionType) Type() protoreflect.EnumType {
	return &file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[0]
}

func (x InteractionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractionType.Descriptor instead.
func (InteractionType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{0}
}

type InputTextType int32

const (
	InputTextType_EMAIL    InputTextType = 0
	InputTextType_PASSWORD InputTextType = 1
)

// Enum value maps for InputTextType.
var (
	InputTextType_name = map[int32]string{
		0: "EMAIL",
		1: "PASSWORD",
	}
	InputTextType_value = map[string]int32{
		"EMAIL":    0,
		"PASSWORD": 1,
	}
)

func (x InputTextType) Enum() *InputTextType {
	p := new(InputTextType)
	*p = x
	return p
}

func (x InputTextType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputTextType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[1].Descriptor()
}

func (InputTextType) Type() protoreflect.EnumType {
	return &file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[1]
}

func (x InputTextType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InputTextType.Descriptor instead.
func (InputTextType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{1}
}

type Gravity int32

const (
	Gravity_TOP Gravity = 0
)

// Enum value maps for Gravity.
var (
	Gravity_name = map[int32]string{
		0: "TOP",
	}
	Gravity_value = map[string]int32{
		"TOP": 0,
	}
)

func (x Gravity) Enum() *Gravity {
	p := new(Gravity)
	*p = x
	return p
}

func (x Gravity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gravity) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[2].Descriptor()
}

func (Gravity) Type() protoreflect.EnumType {
	return &file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[2]
}

func (x Gravity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gravity.Descriptor instead.
func (Gravity) EnumDescriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{2}
}

type ScaleType int32

const (
	ScaleType_CENTER_CROP ScaleType = 0
)

// Enum value maps for ScaleType.
var (
	ScaleType_name = map[int32]string{
		0: "CENTER_CROP",
	}
	ScaleType_value = map[string]int32{
		"CENTER_CROP": 0,
	}
)

func (x ScaleType) Enum() *ScaleType {
	p := new(ScaleType)
	*p = x
	return p
}

func (x ScaleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScaleType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[3].Descriptor()
}

func (ScaleType) Type() protoreflect.EnumType {
	return &file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[3]
}

func (x ScaleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScaleType.Descriptor instead.
func (ScaleType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{3}
}

type Orientation int32

const (
	Orientation_HORIZONTAL Orientation = 0
	Orientation_VERTICAL   Orientation = 1
)

// Enum value maps for Orientation.
var (
	Orientation_name = map[int32]string{
		0: "HORIZONTAL",
		1: "VERTICAL",
	}
	Orientation_value = map[string]int32{
		"HORIZONTAL": 0,
		"VERTICAL":   1,
	}
)

func (x Orientation) Enum() *Orientation {
	p := new(Orientation)
	*p = x
	return p
}

func (x Orientation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Orientation) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[4].Descriptor()
}

func (Orientation) Type() protoreflect.EnumType {
	return &file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[4]
}

func (x Orientation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Orientation.Descriptor instead.
func (Orientation) EnumDescriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{4}
}

type LayoutSize int32

const (
	//default
	LayoutSize_VALUE        LayoutSize = 0
	LayoutSize_MATCH_PARENT LayoutSize = 1
	LayoutSize_WRAP_CONTENT LayoutSize = 2
)

// Enum value maps for LayoutSize.
var (
	LayoutSize_name = map[int32]string{
		0: "VALUE",
		1: "MATCH_PARENT",
		2: "WRAP_CONTENT",
	}
	LayoutSize_value = map[string]int32{
		"VALUE":        0,
		"MATCH_PARENT": 1,
		"WRAP_CONTENT": 2,
	}
)

func (x LayoutSize) Enum() *LayoutSize {
	p := new(LayoutSize)
	*p = x
	return p
}

func (x LayoutSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayoutSize) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[5].Descriptor()
}

func (LayoutSize) Type() protoreflect.EnumType {
	return &file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes[5]
}

func (x LayoutSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayoutSize.Descriptor instead.
func (LayoutSize) EnumDescriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{5}
}

type ActivityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int32 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
}

func (x *ActivityRequest) Reset() {
	*x = ActivityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityRequest) ProtoMessage() {}

func (x *ActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityRequest.ProtoReflect.Descriptor instead.
func (*ActivityRequest) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityRequest) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type ActivityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Activity []*any.Any `protobuf:"bytes,1,rep,name=activity,proto3" json:"activity,omitempty"`
}

func (x *ActivityReply) Reset() {
	*x = ActivityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityReply) ProtoMessage() {}

func (x *ActivityReply) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityReply.ProtoReflect.Descriptor instead.
func (*ActivityReply) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityReply) GetActivity() []*any.Any {
	if x != nil {
		return x.Activity
	}
	return nil
}

type ViewProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentId         int32      `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Id               int32      `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Gravity          Gravity    `protobuf:"varint,3,opt,name=gravity,proto3,enum=CMS.Gravity" json:"gravity,omitempty"`
	LayoutHeightType LayoutSize `protobuf:"varint,4,opt,name=layout_height_type,json=layoutHeightType,proto3,enum=CMS.LayoutSize" json:"layout_height_type,omitempty"`
	HeightValue      int32      `protobuf:"varint,5,opt,name=height_value,json=heightValue,proto3" json:"height_value,omitempty"`
	LayoutWidthType  LayoutSize `protobuf:"varint,6,opt,name=layout_width_type,json=layoutWidthType,proto3,enum=CMS.LayoutSize" json:"layout_width_type,omitempty"`
	WidthValue       int32      `protobuf:"varint,7,opt,name=width_value,json=widthValue,proto3" json:"width_value,omitempty"`
	MarginStart      int32      `protobuf:"varint,8,opt,name=margin_start,json=marginStart,proto3" json:"margin_start,omitempty"`
	MarginEnd        int32      `protobuf:"varint,9,opt,name=margin_end,json=marginEnd,proto3" json:"margin_end,omitempty"`
	MarginLeft       int32      `protobuf:"varint,10,opt,name=margin_left,json=marginLeft,proto3" json:"margin_left,omitempty"`
	MarginTop        int32      `protobuf:"varint,11,opt,name=margin_top,json=marginTop,proto3" json:"margin_top,omitempty"`
	MarginRight      int32      `protobuf:"varint,12,opt,name=margin_right,json=marginRight,proto3" json:"margin_right,omitempty"`
	MarginBottom     int32      `protobuf:"varint,13,opt,name=margin_bottom,json=marginBottom,proto3" json:"margin_bottom,omitempty"`
	Order            int32      `protobuf:"varint,14,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *ViewProperties) Reset() {
	*x = ViewProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewProperties) ProtoMessage() {}

func (x *ViewProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewProperties.ProtoReflect.Descriptor instead.
func (*ViewProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{2}
}

func (x *ViewProperties) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ViewProperties) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ViewProperties) GetGravity() Gravity {
	if x != nil {
		return x.Gravity
	}
	return Gravity_TOP
}

func (x *ViewProperties) GetLayoutHeightType() LayoutSize {
	if x != nil {
		return x.LayoutHeightType
	}
	return LayoutSize_VALUE
}

func (x *ViewProperties) GetHeightValue() int32 {
	if x != nil {
		return x.HeightValue
	}
	return 0
}

func (x *ViewProperties) GetLayoutWidthType() LayoutSize {
	if x != nil {
		return x.LayoutWidthType
	}
	return LayoutSize_VALUE
}

func (x *ViewProperties) GetWidthValue() int32 {
	if x != nil {
		return x.WidthValue
	}
	return 0
}

func (x *ViewProperties) GetMarginStart() int32 {
	if x != nil {
		return x.MarginStart
	}
	return 0
}

func (x *ViewProperties) GetMarginEnd() int32 {
	if x != nil {
		return x.MarginEnd
	}
	return 0
}

func (x *ViewProperties) GetMarginLeft() int32 {
	if x != nil {
		return x.MarginLeft
	}
	return 0
}

func (x *ViewProperties) GetMarginTop() int32 {
	if x != nil {
		return x.MarginTop
	}
	return 0
}

func (x *ViewProperties) GetMarginRight() int32 {
	if x != nil {
		return x.MarginRight
	}
	return 0
}

func (x *ViewProperties) GetMarginBottom() int32 {
	if x != nil {
		return x.MarginBottom
	}
	return 0
}

func (x *ViewProperties) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type LinearLayoutProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View        *ViewProperties `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Orientation Orientation     `protobuf:"varint,2,opt,name=orientation,proto3,enum=CMS.Orientation" json:"orientation,omitempty"`
}

func (x *LinearLayoutProperties) Reset() {
	*x = LinearLayoutProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinearLayoutProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearLayoutProperties) ProtoMessage() {}

func (x *LinearLayoutProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinearLayoutProperties.ProtoReflect.Descriptor instead.
func (*LinearLayoutProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{3}
}

func (x *LinearLayoutProperties) GetView() *ViewProperties {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *LinearLayoutProperties) GetOrientation() Orientation {
	if x != nil {
		return x.Orientation
	}
	return Orientation_HORIZONTAL
}

type ImageProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View      *ViewProperties `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Uri       string          `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	ScaleType ScaleType       `protobuf:"varint,3,opt,name=scale_type,json=scaleType,proto3,enum=CMS.ScaleType" json:"scale_type,omitempty"`
}

func (x *ImageProperties) Reset() {
	*x = ImageProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageProperties) ProtoMessage() {}

func (x *ImageProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageProperties.ProtoReflect.Descriptor instead.
func (*ImageProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{4}
}

func (x *ImageProperties) GetView() *ViewProperties {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *ImageProperties) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ImageProperties) GetScaleType() ScaleType {
	if x != nil {
		return x.ScaleType
	}
	return ScaleType_CENTER_CROP
}

type TextProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View *ViewProperties `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Text string          `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TextProperties) Reset() {
	*x = TextProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextProperties) ProtoMessage() {}

func (x *TextProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextProperties.ProtoReflect.Descriptor instead.
func (*TextProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{5}
}

func (x *TextProperties) GetView() *ViewProperties {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *TextProperties) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ButtonProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View                      *ViewProperties            `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Text                      string                     `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	BackgroundColor           string                     `protobuf:"bytes,3,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	TextColor                 string                     `protobuf:"bytes,4,opt,name=textColor,proto3" json:"textColor,omitempty"`
	InteractionType           InteractionType            `protobuf:"varint,5,opt,name=interaction_type,json=interactionType,proto3,enum=CMS.InteractionType" json:"interaction_type,omitempty"`
	ChangeActivityInteraction *ChangeActivityInteraction `protobuf:"bytes,6,opt,name=change_activity_interaction,json=changeActivityInteraction,proto3" json:"change_activity_interaction,omitempty"`
	RecyclerViewInteraction   *RecyclerViewInteraction   `protobuf:"bytes,7,opt,name=recycler_view_interaction,json=recyclerViewInteraction,proto3" json:"recycler_view_interaction,omitempty"`
	SubmitInteraction         *SubmitInteraction         `protobuf:"bytes,8,opt,name=submit_interaction,json=submitInteraction,proto3" json:"submit_interaction,omitempty"`
}

func (x *ButtonProperties) Reset() {
	*x = ButtonProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ButtonProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonProperties) ProtoMessage() {}

func (x *ButtonProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonProperties.ProtoReflect.Descriptor instead.
func (*ButtonProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{6}
}

func (x *ButtonProperties) GetView() *ViewProperties {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *ButtonProperties) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ButtonProperties) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

func (x *ButtonProperties) GetTextColor() string {
	if x != nil {
		return x.TextColor
	}
	return ""
}

func (x *ButtonProperties) GetInteractionType() InteractionType {
	if x != nil {
		return x.InteractionType
	}
	return InteractionType_CHANGE_ACTIVITY
}

func (x *ButtonProperties) GetChangeActivityInteraction() *ChangeActivityInteraction {
	if x != nil {
		return x.ChangeActivityInteraction
	}
	return nil
}

func (x *ButtonProperties) GetRecyclerViewInteraction() *RecyclerViewInteraction {
	if x != nil {
		return x.RecyclerViewInteraction
	}
	return nil
}

func (x *ButtonProperties) GetSubmitInteraction() *SubmitInteraction {
	if x != nil {
		return x.SubmitInteraction
	}
	return nil
}

type ChangeActivityInteraction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextActivityId  int32 `protobuf:"varint,1,opt,name=next_activity_id,json=nextActivityId,proto3" json:"next_activity_id,omitempty"`
	InvalidateCache bool  `protobuf:"varint,2,opt,name=invalidate_cache,json=invalidateCache,proto3" json:"invalidate_cache,omitempty"`
	AllowBackButton bool  `protobuf:"varint,3,opt,name=allow_back_button,json=allowBackButton,proto3" json:"allow_back_button,omitempty"`
}

func (x *ChangeActivityInteraction) Reset() {
	*x = ChangeActivityInteraction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeActivityInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeActivityInteraction) ProtoMessage() {}

func (x *ChangeActivityInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeActivityInteraction.ProtoReflect.Descriptor instead.
func (*ChangeActivityInteraction) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeActivityInteraction) GetNextActivityId() int32 {
	if x != nil {
		return x.NextActivityId
	}
	return 0
}

func (x *ChangeActivityInteraction) GetInvalidateCache() bool {
	if x != nil {
		return x.InvalidateCache
	}
	return false
}

func (x *ChangeActivityInteraction) GetAllowBackButton() bool {
	if x != nil {
		return x.AllowBackButton
	}
	return false
}

type RecyclerViewInteraction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecycleViewId int32 `protobuf:"varint,1,opt,name=recycle_view_id,json=recycleViewId,proto3" json:"recycle_view_id,omitempty"`
	GoTo          int32 `protobuf:"varint,2,opt,name=go_to,json=goTo,proto3" json:"go_to,omitempty"`
}

func (x *RecyclerViewInteraction) Reset() {
	*x = RecyclerViewInteraction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecyclerViewInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecyclerViewInteraction) ProtoMessage() {}

func (x *RecyclerViewInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecyclerViewInteraction.ProtoReflect.Descriptor instead.
func (*RecyclerViewInteraction) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{8}
}

func (x *RecyclerViewInteraction) GetRecycleViewId() int32 {
	if x != nil {
		return x.RecycleViewId
	}
	return 0
}

func (x *RecyclerViewInteraction) GetGoTo() int32 {
	if x != nil {
		return x.GoTo
	}
	return 0
}

type SubmitInteraction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormId int32 `protobuf:"varint,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
}

func (x *SubmitInteraction) Reset() {
	*x = SubmitInteraction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitInteraction) ProtoMessage() {}

func (x *SubmitInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitInteraction.ProtoReflect.Descriptor instead.
func (*SubmitInteraction) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitInteraction) GetFormId() int32 {
	if x != nil {
		return x.FormId
	}
	return 0
}

type RecyclerViewProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View         *ViewProperties `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	HasFixedSize bool            `protobuf:"varint,2,opt,name=hasFixedSize,proto3" json:"hasFixedSize,omitempty"`
	Orientation  Orientation     `protobuf:"varint,3,opt,name=orientation,proto3,enum=CMS.Orientation" json:"orientation,omitempty"`
}

func (x *RecyclerViewProperties) Reset() {
	*x = RecyclerViewProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecyclerViewProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecyclerViewProperties) ProtoMessage() {}

func (x *RecyclerViewProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecyclerViewProperties.ProtoReflect.Descriptor instead.
func (*RecyclerViewProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{10}
}

func (x *RecyclerViewProperties) GetView() *ViewProperties {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *RecyclerViewProperties) GetHasFixedSize() bool {
	if x != nil {
		return x.HasFixedSize
	}
	return false
}

func (x *RecyclerViewProperties) GetOrientation() Orientation {
	if x != nil {
		return x.Orientation
	}
	return Orientation_HORIZONTAL
}

type TextInputProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View      *ViewProperties `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	TextHint  string          `protobuf:"bytes,2,opt,name=textHint,proto3" json:"textHint,omitempty"`
	TextSize  float32         `protobuf:"fixed32,3,opt,name=textSize,proto3" json:"textSize,omitempty"`
	InputType InputTextType   `protobuf:"varint,4,opt,name=inputType,proto3,enum=CMS.InputTextType" json:"inputType,omitempty"`
}

func (x *TextInputProperties) Reset() {
	*x = TextInputProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextInputProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInputProperties) ProtoMessage() {}

func (x *TextInputProperties) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInputProperties.ProtoReflect.Descriptor instead.
func (*TextInputProperties) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP(), []int{11}
}

func (x *TextInputProperties) GetView() *ViewProperties {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *TextInputProperties) GetTextHint() string {
	if x != nil {
		return x.TextHint
	}
	return ""
}

func (x *TextInputProperties) GetTextSize() float32 {
	if x != nil {
		return x.TextSize
	}
	return 0
}

func (x *TextInputProperties) GetInputType() InputTextType {
	if x != nil {
		return x.InputType
	}
	return InputTextType_EMAIL
}

var File_github_com_hmartins98_Contracts_CMS_CMS_proto protoreflect.FileDescriptor

var file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6d, 0x61,
	0x72, 0x74, 0x69, 0x6e, 0x73, 0x39, 0x38, 0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x2f, 0x43, 0x4d, 0x53, 0x2f, 0x43, 0x4d, 0x53, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x43, 0x4d, 0x53, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x32, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x0d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x22, 0x85, 0x04, 0x0a, 0x0e, 0x56, 0x69, 0x65, 0x77, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x07, 0x67, 0x72, 0x61, 0x76, 0x69, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x47, 0x72,
	0x61, 0x76, 0x69, 0x74, 0x79, 0x52, 0x07, 0x67, 0x72, 0x61, 0x76, 0x69, 0x74, 0x79, 0x12, 0x3d,
	0x0a, 0x12, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x4d, 0x53,
	0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x10, 0x6c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x3b, 0x0a, 0x11, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x4d,
	0x53, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x0f, 0x6c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x57, 0x69, 0x64, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x77, 0x69, 0x64, 0x74, 0x68, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x77, 0x69, 0x64, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x5f, 0x65, 0x6e, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x45, 0x6e, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x4c, 0x65, 0x66,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x6f, 0x70, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x54, 0x6f, 0x70,
	0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x52, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x72, 0x67, 0x69, 0x6e, 0x5f, 0x62, 0x6f,
	0x74, 0x74, 0x6f, 0x6d, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x61, 0x72, 0x67,
	0x69, 0x6e, 0x42, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x75,
	0x0a, 0x16, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x56, 0x69, 0x65,
	0x77, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x04, 0x76, 0x69, 0x65,
	0x77, 0x12, 0x32, 0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x4f, 0x72, 0x69,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7b, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x56, 0x69, 0x65,
	0x77, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x04, 0x76, 0x69, 0x65,
	0x77, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x69, 0x12, 0x2d, 0x0a, 0x0a, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x53, 0x63,
	0x61, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x4d, 0x0a, 0x0e, 0x54, 0x65, 0x78, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0xda, 0x03, 0x0a, 0x10, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x62,
	0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x3f, 0x0a, 0x10,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x5e, 0x0a,
	0x1b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x19, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x58, 0x0a,
	0x19, 0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x72, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x72, 0x56,
	0x69, 0x65, 0x77, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x17,
	0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x12, 0x73, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x73, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9c,
	0x01, 0x0a, 0x19, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x12, 0x2a, 0x0a, 0x11, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x5f,
	0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x42, 0x61, 0x63, 0x6b, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x22, 0x56, 0x0a,
	0x17, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x79,
	0x63, 0x6c, 0x65, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x56, 0x69, 0x65, 0x77, 0x49, 0x64,
	0x12, 0x13, 0x0a, 0x05, 0x67, 0x6f, 0x5f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x67, 0x6f, 0x54, 0x6f, 0x22, 0x2c, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6f,
	0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x6f, 0x72,
	0x6d, 0x49, 0x64, 0x22, 0x99, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x72,
	0x56, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x27,
	0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43,
	0x4d, 0x53, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65,
	0x73, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x22, 0x0a, 0x0c, 0x68, 0x61, 0x73, 0x46, 0x69,
	0x78, 0x65, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x68,
	0x61, 0x73, 0x46, 0x69, 0x78, 0x65, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x32, 0x0a, 0x0b, 0x6f,
	0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x10, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0xa8, 0x01, 0x0a, 0x13, 0x54, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x56, 0x69, 0x65, 0x77,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77,
	0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x78, 0x74, 0x48, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x78, 0x74, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x74, 0x65, 0x78, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x74, 0x65, 0x78, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x43, 0x4d,
	0x53, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x65, 0x78, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x45, 0x0a, 0x0f, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a,
	0x0f, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x49, 0x54, 0x59,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x43, 0x59, 0x43, 0x4c, 0x45, 0x52, 0x5f, 0x56,
	0x49, 0x45, 0x57, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x55, 0x42, 0x4d, 0x49, 0x54, 0x10,
	0x02, 0x2a, 0x28, 0x0a, 0x0d, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x65, 0x78, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x01, 0x2a, 0x12, 0x0a, 0x07, 0x47,
	0x72, 0x61, 0x76, 0x69, 0x74, 0x79, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x4f, 0x50, 0x10, 0x00, 0x2a,
	0x1c, 0x0a, 0x09, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b,
	0x43, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x5f, 0x43, 0x52, 0x4f, 0x50, 0x10, 0x00, 0x2a, 0x2b, 0x0a,
	0x0b, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x0a,
	0x48, 0x4f, 0x52, 0x49, 0x5a, 0x4f, 0x4e, 0x54, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x56, 0x45, 0x52, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x01, 0x2a, 0x3b, 0x0a, 0x0a, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x41, 0x4c, 0x55,
	0x45, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x50, 0x41, 0x52,
	0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x57, 0x52, 0x41, 0x50, 0x5f, 0x43, 0x4f,
	0x4e, 0x54, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x32, 0x3e, 0x0a, 0x03, 0x43, 0x4d, 0x53, 0x12, 0x37,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x14, 0x2e,
	0x43, 0x4d, 0x53, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x43, 0x4d, 0x53, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x4a, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x5f, 0x61, 0x70, 0x70,
	0x42, 0x0a, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x43, 0x4d, 0x53, 0x50, 0x01, 0x5a, 0x23,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6d, 0x61, 0x72, 0x74,
	0x69, 0x6e, 0x73, 0x39, 0x38, 0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f,
	0x43, 0x4d, 0x53, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescOnce sync.Once
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescData = file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDesc
)

func file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescGZIP() []byte {
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescOnce.Do(func() {
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescData)
	})
	return file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDescData
}

var file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_github_com_hmartins98_Contracts_CMS_CMS_proto_goTypes = []interface{}{
	(InteractionType)(0),              // 0: CMS.InteractionType
	(InputTextType)(0),                // 1: CMS.InputTextType
	(Gravity)(0),                      // 2: CMS.Gravity
	(ScaleType)(0),                    // 3: CMS.ScaleType
	(Orientation)(0),                  // 4: CMS.Orientation
	(LayoutSize)(0),                   // 5: CMS.LayoutSize
	(*ActivityRequest)(nil),           // 6: CMS.ActivityRequest
	(*ActivityReply)(nil),             // 7: CMS.ActivityReply
	(*ViewProperties)(nil),            // 8: CMS.ViewProperties
	(*LinearLayoutProperties)(nil),    // 9: CMS.LinearLayoutProperties
	(*ImageProperties)(nil),           // 10: CMS.ImageProperties
	(*TextProperties)(nil),            // 11: CMS.TextProperties
	(*ButtonProperties)(nil),          // 12: CMS.ButtonProperties
	(*ChangeActivityInteraction)(nil), // 13: CMS.ChangeActivityInteraction
	(*RecyclerViewInteraction)(nil),   // 14: CMS.RecyclerViewInteraction
	(*SubmitInteraction)(nil),         // 15: CMS.SubmitInteraction
	(*RecyclerViewProperties)(nil),    // 16: CMS.RecyclerViewProperties
	(*TextInputProperties)(nil),       // 17: CMS.TextInputProperties
	(*any.Any)(nil),                   // 18: google.protobuf.Any
}
var file_github_com_hmartins98_Contracts_CMS_CMS_proto_depIdxs = []int32{
	18, // 0: CMS.ActivityReply.activity:type_name -> google.protobuf.Any
	2,  // 1: CMS.ViewProperties.gravity:type_name -> CMS.Gravity
	5,  // 2: CMS.ViewProperties.layout_height_type:type_name -> CMS.LayoutSize
	5,  // 3: CMS.ViewProperties.layout_width_type:type_name -> CMS.LayoutSize
	8,  // 4: CMS.LinearLayoutProperties.view:type_name -> CMS.ViewProperties
	4,  // 5: CMS.LinearLayoutProperties.orientation:type_name -> CMS.Orientation
	8,  // 6: CMS.ImageProperties.view:type_name -> CMS.ViewProperties
	3,  // 7: CMS.ImageProperties.scale_type:type_name -> CMS.ScaleType
	8,  // 8: CMS.TextProperties.view:type_name -> CMS.ViewProperties
	8,  // 9: CMS.ButtonProperties.view:type_name -> CMS.ViewProperties
	0,  // 10: CMS.ButtonProperties.interaction_type:type_name -> CMS.InteractionType
	13, // 11: CMS.ButtonProperties.change_activity_interaction:type_name -> CMS.ChangeActivityInteraction
	14, // 12: CMS.ButtonProperties.recycler_view_interaction:type_name -> CMS.RecyclerViewInteraction
	15, // 13: CMS.ButtonProperties.submit_interaction:type_name -> CMS.SubmitInteraction
	8,  // 14: CMS.RecyclerViewProperties.view:type_name -> CMS.ViewProperties
	4,  // 15: CMS.RecyclerViewProperties.orientation:type_name -> CMS.Orientation
	8,  // 16: CMS.TextInputProperties.view:type_name -> CMS.ViewProperties
	1,  // 17: CMS.TextInputProperties.inputType:type_name -> CMS.InputTextType
	6,  // 18: CMS.CMS.GetActivity:input_type -> CMS.ActivityRequest
	7,  // 19: CMS.CMS.GetActivity:output_type -> CMS.ActivityReply
	19, // [19:20] is the sub-list for method output_type
	18, // [18:19] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_github_com_hmartins98_Contracts_CMS_CMS_proto_init() }
func file_github_com_hmartins98_Contracts_CMS_CMS_proto_init() {
	if File_github_com_hmartins98_Contracts_CMS_CMS_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinearLayoutProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ButtonProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeActivityInteraction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecyclerViewInteraction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitInteraction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecyclerViewProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextInputProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_hmartins98_Contracts_CMS_CMS_proto_goTypes,
		DependencyIndexes: file_github_com_hmartins98_Contracts_CMS_CMS_proto_depIdxs,
		EnumInfos:         file_github_com_hmartins98_Contracts_CMS_CMS_proto_enumTypes,
		MessageInfos:      file_github_com_hmartins98_Contracts_CMS_CMS_proto_msgTypes,
	}.Build()
	File_github_com_hmartins98_Contracts_CMS_CMS_proto = out.File
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_rawDesc = nil
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_goTypes = nil
	file_github_com_hmartins98_Contracts_CMS_CMS_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CMSClient is the client API for CMS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CMSClient interface {
	GetActivity(ctx context.Context, in *ActivityRequest, opts ...grpc.CallOption) (*ActivityReply, error)
}

type cMSClient struct {
	cc grpc.ClientConnInterface
}

func NewCMSClient(cc grpc.ClientConnInterface) CMSClient {
	return &cMSClient{cc}
}

func (c *cMSClient) GetActivity(ctx context.Context, in *ActivityRequest, opts ...grpc.CallOption) (*ActivityReply, error) {
	out := new(ActivityReply)
	err := c.cc.Invoke(ctx, "/CMS.CMS/GetActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CMSServer is the server API for CMS service.
type CMSServer interface {
	GetActivity(context.Context, *ActivityRequest) (*ActivityReply, error)
}

// UnimplementedCMSServer can be embedded to have forward compatible implementations.
type UnimplementedCMSServer struct {
}

func (*UnimplementedCMSServer) GetActivity(context.Context, *ActivityRequest) (*ActivityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivity not implemented")
}

func RegisterCMSServer(s *grpc.Server, srv CMSServer) {
	s.RegisterService(&_CMS_serviceDesc, srv)
}

func _CMS_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMSServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CMS.CMS/GetActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMSServer).GetActivity(ctx, req.(*ActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CMS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CMS.CMS",
	HandlerType: (*CMSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActivity",
			Handler:    _CMS_GetActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/hmartins98/Contracts/CMS/CMS.proto",
}
