// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: github.com/hmartins98/Contracts/API/API.proto

package API

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Status int32

const (
	Status_Success Status = 0
	Status_Fail    Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Success",
		1: "Fail",
	}
	Status_value = map[string]int32{
		"Success": 0,
		"Fail":    1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_hmartins98_Contracts_API_API_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_github_com_hmartins98_Contracts_API_API_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_API_API_proto_rawDescGZIP(), []int{0}
}

type AnswerFormRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormId   int32            `protobuf:"varint,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Response []*ResponseField `protobuf:"bytes,2,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *AnswerFormRequest) Reset() {
	*x = AnswerFormRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_API_API_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerFormRequest) ProtoMessage() {}

func (x *AnswerFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_API_API_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerFormRequest.ProtoReflect.Descriptor instead.
func (*AnswerFormRequest) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_API_API_proto_rawDescGZIP(), []int{0}
}

func (x *AnswerFormRequest) GetFormId() int32 {
	if x != nil {
		return x.FormId
	}
	return 0
}

func (x *AnswerFormRequest) GetResponse() []*ResponseField {
	if x != nil {
		return x.Response
	}
	return nil
}

type AnswerFormReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId int32  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Status     Status `protobuf:"varint,2,opt,name=status,proto3,enum=API.Status" json:"status,omitempty"`
	Message    string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AnswerFormReply) Reset() {
	*x = AnswerFormReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_API_API_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerFormReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerFormReply) ProtoMessage() {}

func (x *AnswerFormReply) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_API_API_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerFormReply.ProtoReflect.Descriptor instead.
func (*AnswerFormReply) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_API_API_proto_rawDescGZIP(), []int{1}
}

func (x *AnswerFormReply) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *AnswerFormReply) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Success
}

func (x *AnswerFormReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResponseField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldName  string `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldValue string `protobuf:"bytes,2,opt,name=field_value,json=fieldValue,proto3" json:"field_value,omitempty"`
}

func (x *ResponseField) Reset() {
	*x = ResponseField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_hmartins98_Contracts_API_API_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseField) ProtoMessage() {}

func (x *ResponseField) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_hmartins98_Contracts_API_API_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseField.ProtoReflect.Descriptor instead.
func (*ResponseField) Descriptor() ([]byte, []int) {
	return file_github_com_hmartins98_Contracts_API_API_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseField) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *ResponseField) GetFieldValue() string {
	if x != nil {
		return x.FieldValue
	}
	return ""
}

var File_github_com_hmartins98_Contracts_API_API_proto protoreflect.FileDescriptor

var file_github_com_hmartins98_Contracts_API_API_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6d, 0x61,
	0x72, 0x74, 0x69, 0x6e, 0x73, 0x39, 0x38, 0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x73, 0x2f, 0x41, 0x50, 0x49, 0x2f, 0x41, 0x50, 0x49, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x41, 0x50, 0x49, 0x22, 0x5c, 0x0a, 0x11, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x46, 0x6f,
	0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6f, 0x72,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d,
	0x49, 0x64, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x71, 0x0a, 0x0f, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4f, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x1f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x46, 0x61, 0x69, 0x6c, 0x10, 0x01, 0x32, 0x41, 0x0a, 0x03, 0x41, 0x50, 0x49, 0x12, 0x3a,
	0x0a, 0x0a, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x16, 0x2e, 0x41,
	0x50, 0x49, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x41, 0x50, 0x49, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x4a, 0x0a, 0x15, 0x63, 0x6f,
	0x6d, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x5f,
	0x61, 0x70, 0x70, 0x42, 0x0a, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x41, 0x50, 0x49, 0x50,
	0x01, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6d,
	0x61, 0x72, 0x74, 0x69, 0x6e, 0x73, 0x39, 0x38, 0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2f, 0x41, 0x50, 0x49, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_hmartins98_Contracts_API_API_proto_rawDescOnce sync.Once
	file_github_com_hmartins98_Contracts_API_API_proto_rawDescData = file_github_com_hmartins98_Contracts_API_API_proto_rawDesc
)

func file_github_com_hmartins98_Contracts_API_API_proto_rawDescGZIP() []byte {
	file_github_com_hmartins98_Contracts_API_API_proto_rawDescOnce.Do(func() {
		file_github_com_hmartins98_Contracts_API_API_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_hmartins98_Contracts_API_API_proto_rawDescData)
	})
	return file_github_com_hmartins98_Contracts_API_API_proto_rawDescData
}

var file_github_com_hmartins98_Contracts_API_API_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_hmartins98_Contracts_API_API_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_hmartins98_Contracts_API_API_proto_goTypes = []interface{}{
	(Status)(0),               // 0: API.Status
	(*AnswerFormRequest)(nil), // 1: API.AnswerFormRequest
	(*AnswerFormReply)(nil),   // 2: API.AnswerFormReply
	(*ResponseField)(nil),     // 3: API.ResponseField
}
var file_github_com_hmartins98_Contracts_API_API_proto_depIdxs = []int32{
	3, // 0: API.AnswerFormRequest.response:type_name -> API.ResponseField
	0, // 1: API.AnswerFormReply.status:type_name -> API.Status
	1, // 2: API.API.AnswerForm:input_type -> API.AnswerFormRequest
	2, // 3: API.API.AnswerForm:output_type -> API.AnswerFormReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_hmartins98_Contracts_API_API_proto_init() }
func file_github_com_hmartins98_Contracts_API_API_proto_init() {
	if File_github_com_hmartins98_Contracts_API_API_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_hmartins98_Contracts_API_API_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerFormRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_API_API_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerFormReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_hmartins98_Contracts_API_API_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_hmartins98_Contracts_API_API_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_hmartins98_Contracts_API_API_proto_goTypes,
		DependencyIndexes: file_github_com_hmartins98_Contracts_API_API_proto_depIdxs,
		EnumInfos:         file_github_com_hmartins98_Contracts_API_API_proto_enumTypes,
		MessageInfos:      file_github_com_hmartins98_Contracts_API_API_proto_msgTypes,
	}.Build()
	File_github_com_hmartins98_Contracts_API_API_proto = out.File
	file_github_com_hmartins98_Contracts_API_API_proto_rawDesc = nil
	file_github_com_hmartins98_Contracts_API_API_proto_goTypes = nil
	file_github_com_hmartins98_Contracts_API_API_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	AnswerForm(ctx context.Context, in *AnswerFormRequest, opts ...grpc.CallOption) (*AnswerFormReply, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) AnswerForm(ctx context.Context, in *AnswerFormRequest, opts ...grpc.CallOption) (*AnswerFormReply, error) {
	out := new(AnswerFormReply)
	err := c.cc.Invoke(ctx, "/API.API/AnswerForm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	AnswerForm(context.Context, *AnswerFormRequest) (*AnswerFormReply, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) AnswerForm(context.Context, *AnswerFormRequest) (*AnswerFormReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnswerForm not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_AnswerForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).AnswerForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API.API/AnswerForm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).AnswerForm(ctx, req.(*AnswerFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "API.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnswerForm",
			Handler:    _API_AnswerForm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/hmartins98/Contracts/API/API.proto",
}
